#!/usr/bin/env node
/* Bundle what a published page needs (src/app/visitor.ts) into app/visitor.js. Generated; do not edit. Run after changing render.ts, behave.ts, houses.ts or theme.ts. */
import { buildSync } from "esbuild";
import { resolve, dirname } from "node:path";
const root = resolve(dirname(new URL(import.meta.url).pathname), "..");
buildSync({ entryPoints: [`${root}/src/app/visitor.ts`], bundle: true, format: "iife", platform: "browser", target: "es2020", minify: true, outfile: `${root}/app/visitor.js`, banner: { js: "/* Generated by scripts/build-visitor.mjs from src/app. Do not edit. */" }, logLevel: "info" });
